# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fndkmVaiSJj5_upsc2KgDs0GY2Ob-4Z
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the data
df = pd.read_csv('runway_data.csv')

# Define our columns
nasa_cols = ['NASA_Mental', 'NASA_Physical', 'NASA_Temporal', 'NASA_Performance', 'NASA_Effort', 'NASA_Frustration']
swat_cols = ['SWAT_Time', 'SWAT_Mental', 'SWAT_Stress']

# Ensure task names are in the right order for the charts
task_order = ['Simple Image Generation', 'Complex Image Generation', 'Video Generation']
df['Task'] = pd.Categorical(df['Task'], categories=task_order, ordered=True)

print("==== TABLE 2: NASA-TLX SCORES ====")
for task in task_order:
    task_data = df[df['Task'] == task]
    print(f"\n--- {task} ---")
    for col in nasa_cols:
        mean = task_data[col].mean()
        std = task_data[col].std()
        print(f"{col.replace('NASA_', '')}: {mean:.1f} ± {std:.1f}")

print("\n\n==== TABLE 3: SWAT SCORES ====")
for task in task_order:
    task_data = df[df['Task'] == task]
    print(f"\n--- {task} ---")
    for col in swat_cols:
        mean = task_data[col].mean()
        std = task_data[col].std()
        print(f"{col.replace('SWAT_', '')}: {mean:.1f} ± {std:.1f}")

# --- Generate NASA Chart ---
nasa_means = df.groupby('Task', observed=False)[nasa_cols].mean().T
nasa_means.index = [col.replace('NASA_', '') for col in nasa_means.index] # Clean up labels

ax1 = nasa_means.plot(kind='bar', figsize=(10, 6), color=['#a8b8d8', '#f4a5a5', '#e2d5c3'], edgecolor='gray')
plt.title('NASA-TLX Score Distribution', fontsize=14, fontweight='bold')
plt.ylabel('Score', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='')
plt.tight_layout()
plt.savefig('NASA_Chart.png', dpi=300) # Saves the high-res image
plt.show()

# --- Generate SWAT Chart ---
swat_means = df.groupby('Task', observed=False)[swat_cols].mean().T
swat_means.index = [col.replace('SWAT_', '').replace('_', ' ') + ' Load' for col in swat_means.index] # Clean labels

ax2 = swat_means.plot(kind='bar', figsize=(8, 5), color=['#a8b8d8', '#f4a5a5', '#e2d5c3'], edgecolor='gray')
plt.title('SWAT Score Analysis', fontsize=14, fontweight='bold')
plt.ylabel('Score', fontsize=12)
plt.xticks(rotation=0)
plt.legend(title='')
plt.ylim(0, 5) # SWAT is on a smaller scale
plt.tight_layout()
plt.savefig('SWAT_Chart.png', dpi=300) # Saves the high-res image
plt.show()