# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fndkmVaiSJj5_upsc2KgDs0GY2Ob-4Z
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the data
df = pd.read_csv('runway_data.csv')

# Define our columns
nasa_cols = ['NASA_Mental', 'NASA_Physical', 'NASA_Temporal', 'NASA_Performance', 'NASA_Effort', 'NASA_Frustration']
swat_cols = ['SWAT_Time', 'SWAT_Mental', 'SWAT_Stress']

# Ensure task names are in the right order
task_order = ['Simple Image Generation', 'Complex Image Generation', 'Video Generation']
df['Task'] = pd.Categorical(df['Task'], categories=task_order, ordered=True)

# --- Helper function to add labels on top of bars ---
def add_labels(ax):
    for p in ax.patches:
        ax.annotate(f'{p.get_height():.1f}',
                    (p.get_x() + p.get_width() / 2., p.get_height()),
                    ha='center', va='center',
                    xytext=(0, 9),
                    textcoords='offset points',
                    fontsize=9,
                    fontweight='bold')

# --- Generate NASA Chart ---
nasa_means = df.groupby('Task', observed=False)[nasa_cols].mean().T
nasa_means.index = [col.replace('NASA_', '') for col in nasa_means.index]

ax1 = nasa_means.plot(kind='bar', figsize=(12, 7), color=['#a8b8d8', '#f4a5a5', '#e2d5c3'], edgecolor='gray')
add_labels(ax1) # Adds the numbers above the bars

plt.title('NASA-TLX Score Distribution', fontsize=14, fontweight='bold')
plt.ylabel('Score', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.ylim(0, 25) # Give some headspace for the labels
plt.legend(title='', loc='upper left')
plt.tight_layout()
plt.savefig('NASA_Chart_Labeled.png', dpi=300)
plt.show()

# --- Generate SWAT Chart ---
swat_means = df.groupby('Task', observed=False)[swat_cols].mean().T
swat_means.index = [col.replace('SWAT_', '').replace('_', ' ') + ' Load' for col in swat_means.index]

ax2 = swat_means.plot(kind='bar', figsize=(10, 6), color=['#a8b8d8', '#f4a5a5', '#e2d5c3'], edgecolor='gray')
add_labels(ax2) # Adds the numbers above the bars

plt.title('SWAT Score Analysis', fontsize=14, fontweight='bold')
plt.ylabel('Score', fontsize=12)
plt.xticks(rotation=0)
plt.ylim(0, 4) # Capped at 4 to show labels clearly on a 3-point scale
plt.legend(title='', loc='upper left')
plt.tight_layout()
plt.savefig('SWAT_Chart_Labeled.png', dpi=300)
plt.show()